version: '3.1'
services:
  typesense:
    image: typesense/typesense:0.16.1
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    volumes:
      - ./data:/data
    ports:
      - 8108:8108
